# Generated by Django 4.2.21 on 2025-10-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student_id', models.IntegerField()),
                ('section', models.CharField(max_length=5)),
                ('degree', models.CharField(max_length=4)),
            ],
        ),
    ]
