GET http://127.0.0.1:8000/api/products/5/ HTTP/1.1

###
GET http://127.0.0.1:8000/api/orders/  HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMzkwMjcwLCJpYXQiOjE3NjAzODk5NzAsImp0aSI6ImVjNGUzMWM0M2I1NzRiZDhiMzI2YmJmNGNjZTMzZmFkIiwidXNlcl9pZCI6IjQifQ.RWdCLOgkexFURloYiZ2TKpQ-riho-XEsQGBYrV9LbzI

###

PUT  http://127.0.0.1:8000/api/products/5/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMzkwMjcwLCJpYXQiOjE3NjAzODk5NzAsImp0aSI6ImVjNGUzMWM0M2I1NzRiZDhiMzI2YmJmNGNjZTMzZmFkIiwidXNlcl9pZCI6IjQifQ.RWdCLOgkexFURloYiZ2TKpQ-riho-XEsQGBYrV9LbzI

{
    "name":"TV",
    "price":300,
    "stock":14,
    "description":"An amazing tv "
}
###
DELETE  http://127.0.0.1:8000/api/products/5/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMzgzNjIwLCJpYXQiOjE3NjAzODMzMjAsImp0aSI6IjExYWJhMmRiNzdmNjQ1MmFiYmM3ZTY3NjA3ZDJmNmRmIiwidXNlcl9pZCI6IjIifQ.BNVG0Q-_O97KhFZe5t6jhpPAyh_qN51IjoWRbNznlSE

###

POST  http://127.0.0.1:8000/api/products/ 
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMzgzNjIwLCJpYXQiOjE3NjAzODMzMjAsImp0aSI6IjExYWJhMmRiNzdmNjQ1MmFiYmM3ZTY3NjA3ZDJmNmRmIiwidXNlcl9pZCI6IjIifQ.BNVG0Q-_O97KhFZe5t6jhpPAyh_qN51IjoWRbNznlSE
{
    "name":"TV",
    "price":300,
    "stock":14,
    "description":"An amazing tv "
}

###

POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username": "enemy",
    "password": "enemy"
}
 
###
GET http://127.0.0.1:8000/api/user-orders/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMzcwNDY3LCJpYXQiOjE3NjAzNzAxNjcsImp0aSI6IjJhZjdjYmMwNzViODQ4YTI4MDExNWVjOTg5YWY5YmM0IiwidXNlcl9pZCI6IjIifQ._Zq35YJsZE1CAFeQA4EFxzNXNkFyIMmZlos37MYbli4

###

POST http://127.0.0.1:8000/api/token/refresh
Content-Type: application/json

{
    "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDQ1OTQzMCwiaWF0IjoxNzYwMzczMDMwLCJqdGkiOiIwYTU2YmYyMTdlZjU0ZjhiYWMwMmViZWZjYTJiY2Y3ZSIsInVzZXJfaWQiOiIyIn0.Jg2tWUX569EuWSyNex_4bglvntjSD1tCcJCo8bKnV8c"
}
###


POST http://127.0.0.1:8000/api/orders/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNDQ0OTgzLCJpYXQiOjE3NjA0NDQ2ODMsImp0aSI6Ijk4ZTUwYzcyYjdhYjQyNzRhOWU1NzgyZGI5YjE2N2FlIiwidXNlcl9pZCI6IjIifQ.rd8WAX2WlM7s-bgMJt8PBC_9rBHEo7GokfL2imhW1gY

{
  "status": "Pending",
  "items": [
    { "product": 2, "quantity": 2 },
    { "product": 3, "quantity": 1 }
  ]
}